import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

import Footer from "./components/layouts/Footer";
import MiniNavbar from "./components/layouts/MiniNavbar";

import FilteringBar from "./components/layouts/FilteringBar";
import Navbar from "./components/layouts/Navbar";
import LinkBar from "./components/layouts/LinkBar";


const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "TechSoi",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased min-h-svh flex flex-col`}
      >
        <MiniNavbar />
        <Navbar/>
        <LinkBar/>
        {/* <MobileScrolableNav /> */}
        <FilteringBar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
